version: '3.2'
services:
  jupyter:
    build: .
    volumes:
      - $PWD:/tmp/working
      - type: bind
        source: ./kaggle.json
        target: /root/.kaggle/kaggle.json
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser